name: 'MacOS-CI Python-3.11'

on:
  workflow_dispatch:

jobs:
  force-python-back-to-3-11:
    name: Force Python back to v3.11
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-12
        python-version:
          - 3.11

    steps:
      - name: Set up Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c #v5.0.0
        with:
          python-version: ${{ matrix.python-version }}
          check-latest: true
